spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT}
            client_secret: ${KAKAO_SECRET}
            client-name: kakao
            redirect-uri: '{baseUrl}/login/oauth2/code/kakao'
            client-authentication-method: client_secret_post # kakao는 인증 토큰 발급 요청 메서드가 post이다. (최근 버전에는 작성 방법이 이렇게 바뀌었다.)
            authorization-grant-type: authorization_code
            scope: # kakao 개인 정보 동의 항목 설정의 ID 값
              - profile_nickname
              - profile_image

          naver:
            client-id: ${NAVER_CLIENT}
            client_secret: ${NAVER_SECRET}
            client-name: naver
            redirect-uri: '{baseUrl}/login/oauth2/code/naver'
            authorization-grant-type: authorization_code
#            scope: # naver는 scope를 설정할 필요가 없음
#              - name
#              - email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 유저 정보 조회 시 반환되는 최상위 필드명으로 해야 한다.

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # response라는 키값으로 네이버가 반환함